# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
#from selenium.webdriver.support.wait import WebDriverWait
#from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


# #class TestPython():
#     def setup_method(self, method):
#         self.driver = webdriver.Chrome()
#         self.vars = {}
#
#     def teardown_method(self, method):
#         self.driver.quit()
#
#     def test_python(self):
#         # Test name: python5
#         # Step # | name | target | value
#         # 1 | open | / |
#         self.driver.get("https://www.w3schools.com/")
#         # 2 | setWindowSize | maximize
#         self.driver.maximize_window()
#         # 3 | click | id=search2 |
#         self.driver.find_element(By.ID, "search2").click()
#         # 4 | type | id=search2 | python
#         self.driver.find_element(By.ID, "search2").send_keys("python")
#         # 5 | click | id=learntocode_searchbtn |
#         self.driver.find_element(By.ID, "learntocode_searchbtn").click()
#         time.sleep(2)
#         # 6 | click | linkText=Next ❯ |
#         self.driver.find_element(By.LINK_TEXT, "Next ❯").click()
#         # 7 | click | linkText=❮ Previous |
#         self.driver.find_element(By.LINK_TEXT, "❮ Previous").click()
#         # 8 | click | linkText=❮ Home |
#         self.driver.find_element(By.LINK_TEXT, "❮ Home").click()
#
